### ISSUE TITLE
[Device request]: ir sensor

### ISSUE THREAD

**Issue by julianborghuis** [athombv/com.tuya#213]
### Device information

Please add the ir sensor
![image](https://github.com/user-attachments/assets/05161160-16ed-4744-bc27-ba56f987d9bc)

### Device specification

![IMG_4590](https://github.com/user-attachments/assets/ffbfe2ed-0674-443f-bddc-9e5b4611d94d)

**Comment by julianborghuis** [comment]
How can i get those?

**Comment by julianborghuis** [comment]
I cant find this ir sensor otherwise?

**Comment by bobvandevijver** [comment]
Follow the instruction which is clearly noted when opening a new ticket (which you have now seen twice). But even then I wouldn't  count on an IR sensor being added, because as far as I know it is not a device that can do something on its own within Tuya. It will always be linked with a different device. You can also control it using the already offered default flow cards that every other device has.
