### ISSUE TITLE
[Device request]: woox R7048 temperature sensor on Homey

### ISSUE THREAD

**Issue by Uffesr** [athombv/com.tuya#256]
### Device information

I have several temperature and Humidity Devices WOOX R7048 that was connected to earlier SmartThings setup. I have not succes connection this with homey. Have tried different Tuya apps, byt it only shows up like a basic on off switch. I guess many have the same problem as woox i sold om the danish marked by serveral channels. Hope You Can find a solution. BR Uffe

### Device specification

..

**Comment by Uffesr** [comment]
I have several temperature and Humidity Devices WOOX R7048 that was connected to earlier SmartThings setup. I have not succes connection this with homey. Have tried different Tuya apps, byt it only shows up like a basic om off switch. I guess many have the same problem as woox i sold om the danish marked by serveral channels. Hope You Can find a solution. BR Uffe

**Comment by bobvandevijver** [comment]
I believe this is a Zigbee device, while this app is only for WiFi devices. You could try to use a Tuya Zigbee bridge, but I cannot give any guarantee that that will work. The other option is using the Tuya Zigbee community app (make sure to install the test version), and otherwise you can try to request it there: https://github.com/JohanBendz/com.tuya.zigbee.
