### ISSUE TITLE
fan_speed_percent not valid for all Tuya fan models

### ISSUE THREAD

**Issue by gslender** [athombv/com.tuya#298]
### Homey version

v12.x

### Tuya app version

latest (how do you know if you're using the repo)

### Description

As per this Tuya developer guide, there are different ways to enable a fan speed, and the fan_speed_percent is not always correct.

https://developer.tuya.com/en/docs/iot/fskg?id=Kbcs1e383bnra

As such, I get a error and the fan speed has not change. 

<img width="669" alt="image" src="https://github.com/user-attachments/assets/48199ec4-6bbb-41b2-9e4a-89060fb57792" />

Changing the fan speed via the Tuya app works fine. This feature was working several months ago, and a recent update to the homey tuya app broke this.

**Comment by bobvandevijver** [comment]
You are referring to the documentation of a product type (fskg) that is not support by this app. For the supported devices we already determine, based on the device specification, whether we use `fan_speed` or `fan_speed_percent`.

I'm also missing the version you are using (from repo you can share the commit and/or branch) and the device specification, which is mentioned in the issue template as a reason to close this.

All development for this app is currently on hold due to the Tuya situation. See #295 and the community topic linked there.
